### PR TITLE
Testing on Tic Tac Toe game

### PR DESCRIPTION
**Pull request by NiiazalyDzhumaliev**
We wrote tests for functions for the Tic Tac Toe game using Jest.
Please kindly review our code.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @NiiazalyDzhumaliev and @paulzay 
### You have done really well so far :clap: However, you have a few issues to fix:-
- [ ] Install all the required dependencies and run linting commands `npx eslint .` if error, kindly solve the issues - [follow this guide](https://github.com/microverseinc/linters-config/tree/master/javascript)
- [ ] The start script is also not working, it gives an error, install the required dependencies and run the command again
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by NiiazalyDzhumaliev** [comment]
Eslint doesn't show any errors, as shown in GitHub's actions. 
What does that mean 'start scripts'?

**Comment by rOluochKe** [comment]
> Eslint doesn't show any errors, as shown in GitHub's actions.
> What does that mean 'start scripts'?

Start script in the package.json

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team
### Following the previous review. See the images below for the errors, I get:-
- [ ] When I run the command npx eslint . I get this error
config
- [ ] The start script in the package.json
start
### For the two above errors, install all the required dependencies and configure them properly as recommended by Microverse. [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/javascript)
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by NiiazalyDzhumaliev** [comment]
According to [this guide](https://github.com/microverseinc/linters-config/tree/master/javascript) it needs to run `npm install --save-dev eslint@6.8.x eslint-config-airbnb-base@14.1.x eslint-plugin-import@2.20.x babel-eslint@10.1.x`

To run tests we need `npm install` then `npm run test`.

**Comment by NiiazalyDzhumaliev** [comment]
If you have any suggestions I am glad to follow.

**Comment by rOluochKe** [comment]
> If you have any suggestions I am glad to follow.

Not really, if you read the article carefully, there are two sections, 
1. eslint - [link](https://github.com/microverseinc/linters-config/tree/master/javascript#eslint)
2. stylelint - [link](https://github.com/microverseinc/linters-config/tree/master/javascript#stylelint)

**Review by rOluochKe — CHANGES_REQUESTED** [review]
### Kindly follow the link to the article I have shared with you earlier, install all eslint and stylelint dependencies then do configuration and run their command from the article. If errors, kindly solve the issues.
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by NiiazalyDzhumaliev** [comment]
Add the dependencies, and all checks passed.

**Review by rOluochKe — APPROVED** [review]
Hello Team
### You got it right, well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
